# Generated by Django 2.2.6 on 2019-11-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.CharField(choices=[('e', 'Electro'), ('f', 'Fire'), ('g', 'Grass'), ('w', 'Water')], max_length=1)),
                ('catch_date', models.DateField()),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PokemonTrainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
