# Generated by Django 2.2.6 on 2019-11-10 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Homework1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='catch_date',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Homework1.PokemonTrainer'),
        ),
    ]
