# Generated by Django 2.2.6 on 2019-11-10 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Homework1', '0002_auto_20191110_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='catch_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
