# Generated by Django 2.2.6 on 2019-11-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homework1', '0003_pokemon_catch_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='pokemon_trainer',
            new_name='trainer',
        ),
    ]
