# Generated by Django 2.2.6 on 2019-11-10 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homework1', '0004_auto_20191110_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='catch_date',
            field=models.DateField(default=datetime.date(2019, 11, 10)),
        ),
    ]
